/*
 * generated by Xtext 2.17.0
 */
package com.foliage.xenia.ide

import com.foliage.xenia.XeniaRuntimeModule
import com.foliage.xenia.XeniaStandaloneSetup
import com.google.inject.Guice
import org.eclipse.xtext.util.Modules2

/**
 * Initialization support for running Xtext languages as language servers.
 */
class XeniaIdeSetup extends XeniaStandaloneSetup {

	override createInjector() {
		Guice.createInjector(Modules2.mixin(new XeniaRuntimeModule, new XeniaIdeModule))
	}
	
}
