/*
 * generated by Xtext 2.17.0
 */
package com.foliage.xenia.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class XeniaAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("com/foliage/xenia/parser/antlr/internal/InternalXenia.tokens");
	}
}
