/*
 * generated by Xtext 2.17.0
 */
package com.foliage.xenia.ui

import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
class XeniaUiModule extends AbstractXeniaUiModule {
}
