/**
 * generated by Xtext 2.17.0
 */
package com.foliage.xenia.xenia;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Info Entity</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.foliage.xenia.xenia.InfoEntity#getEntries <em>Entries</em>}</li>
 *   <li>{@link com.foliage.xenia.xenia.InfoEntity#getInfoValue <em>Info Value</em>}</li>
 * </ul>
 *
 * @see com.foliage.xenia.xenia.XeniaPackage#getInfoEntity()
 * @model
 * @generated
 */
public interface InfoEntity extends EObject
{
  /**
   * Returns the value of the '<em><b>Entries</b></em>' attribute list.
   * The list contents are of type {@link java.lang.String}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Entries</em>' attribute list.
   * @see com.foliage.xenia.xenia.XeniaPackage#getInfoEntity_Entries()
   * @model unique="false"
   * @generated
   */
  EList<String> getEntries();

  /**
   * Returns the value of the '<em><b>Info Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Info Value</em>' attribute.
   * @see #setInfoValue(String)
   * @see com.foliage.xenia.xenia.XeniaPackage#getInfoEntity_InfoValue()
   * @model
   * @generated
   */
  String getInfoValue();

  /**
   * Sets the value of the '{@link com.foliage.xenia.xenia.InfoEntity#getInfoValue <em>Info Value</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Info Value</em>' attribute.
   * @see #getInfoValue()
   * @generated
   */
  void setInfoValue(String value);

} // InfoEntity
