/**
 * generated by Xtext 2.17.0
 */
package com.foliage.xenia.xenia;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Linked Property</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.foliage.xenia.xenia.LinkedProperty#getName <em>Name</em>}</li>
 *   <li>{@link com.foliage.xenia.xenia.LinkedProperty#getInner_name <em>Inner name</em>}</li>
 * </ul>
 *
 * @see com.foliage.xenia.xenia.XeniaPackage#getLinkedProperty()
 * @model
 * @generated
 */
public interface LinkedProperty extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see com.foliage.xenia.xenia.XeniaPackage#getLinkedProperty_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link com.foliage.xenia.xenia.LinkedProperty#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Inner name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Inner name</em>' attribute.
   * @see #setInner_name(String)
   * @see com.foliage.xenia.xenia.XeniaPackage#getLinkedProperty_Inner_name()
   * @model
   * @generated
   */
  String getInner_name();

  /**
   * Sets the value of the '{@link com.foliage.xenia.xenia.LinkedProperty#getInner_name <em>Inner name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Inner name</em>' attribute.
   * @see #getInner_name()
   * @generated
   */
  void setInner_name(String value);

} // LinkedProperty
