/**
 * generated by Xtext 2.17.0
 */
package com.foliage.xenia.xenia;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Mapped Entity</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.foliage.xenia.xenia.MappedEntity#getProp <em>Prop</em>}</li>
 *   <li>{@link com.foliage.xenia.xenia.MappedEntity#getSites <em>Sites</em>}</li>
 * </ul>
 *
 * @see com.foliage.xenia.xenia.XeniaPackage#getMappedEntity()
 * @model
 * @generated
 */
public interface MappedEntity extends EObject
{
  /**
   * Returns the value of the '<em><b>Prop</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Prop</em>' attribute.
   * @see #setProp(String)
   * @see com.foliage.xenia.xenia.XeniaPackage#getMappedEntity_Prop()
   * @model
   * @generated
   */
  String getProp();

  /**
   * Sets the value of the '{@link com.foliage.xenia.xenia.MappedEntity#getProp <em>Prop</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Prop</em>' attribute.
   * @see #getProp()
   * @generated
   */
  void setProp(String value);

  /**
   * Returns the value of the '<em><b>Sites</b></em>' containment reference list.
   * The list contents are of type {@link com.foliage.xenia.xenia.LinkedProperty}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Sites</em>' containment reference list.
   * @see com.foliage.xenia.xenia.XeniaPackage#getMappedEntity_Sites()
   * @model containment="true"
   * @generated
   */
  EList<LinkedProperty> getSites();

} // MappedEntity
