/**
 * generated by Xtext 2.17.0
 */
package com.foliage.xenia.xenia;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Site</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see com.foliage.xenia.xenia.XeniaPackage#getSite()
 * @model
 * @generated
 */
public interface Site extends SuperSite
{
} // Site
