/**
 * generated by Xtext 2.17.0
 */
package com.foliage.xenia.xenia;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Site</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.foliage.xenia.xenia.Site#getName <em>Name</em>}</li>
 *   <li>{@link com.foliage.xenia.xenia.Site#getSites <em>Sites</em>}</li>
 * </ul>
 *
 * @see com.foliage.xenia.xenia.XeniaPackage#getSite()
 * @model
 * @generated
 */
public interface Site extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see com.foliage.xenia.xenia.XeniaPackage#getSite_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link com.foliage.xenia.xenia.Site#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Sites</b></em>' containment reference list.
   * The list contents are of type {@link com.foliage.xenia.xenia.Site}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Sites</em>' containment reference list.
   * @see com.foliage.xenia.xenia.XeniaPackage#getSite_Sites()
   * @model containment="true"
   * @generated
   */
  EList<Site> getSites();

} // Site
