/*
 * generated by Xtext 2.17.0
 */
package com.foliage.xenia.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.validation.AbstractDeclarativeValidator;

public abstract class AbstractXeniaValidator extends AbstractDeclarativeValidator {
	
	@Override
	protected List<EPackage> getEPackages() {
		List<EPackage> result = new ArrayList<EPackage>();
		result.add(com.foliage.xenia.xenia.XeniaPackage.eINSTANCE);
		return result;
	}
}
