/**
 * generated by Xtext 2.17.0
 */
package com.foliage.xenia.ui;

import com.foliage.xenia.ui.AbstractXeniaUiModule;
import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class XeniaUiModule extends AbstractXeniaUiModule {
  public XeniaUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
