/*
 * generated by Xtext 2.17.0
 */
package com.foliage.xenia.tests

import com.foliage.xenia.xenia.Model
import com.google.inject.Inject
import org.eclipse.xtext.testing.InjectWith
import org.eclipse.xtext.testing.extensions.InjectionExtension
import org.eclipse.xtext.testing.util.ParseHelper
import org.junit.jupiter.api.Assertions
import org.junit.jupiter.api.Test
import org.junit.jupiter.api.^extension.ExtendWith

@ExtendWith(InjectionExtension)
@InjectWith(XeniaInjectorProvider)
class XeniaParsingTest {
	@Inject
	ParseHelper<Model> parseHelper
	
	@Test
	def void loadModel() {
		val result = parseHelper.parse('''
			app foliage has pages [
				@Home,
				@News with modal (@Login),
				@Contact
			]
			//with: "Cake"
			mode: DEV
			map: [
				@Home -> (@News, @Contact),
				@News -> (@Contact)
			]
			info: [
				@Home -> mod: "today", freq: "weekly",
				@News -> prio: "0.9", mod: "01.09.2019"
			]
			
		''')
		Assertions.assertNotNull(result)
		val errors = result.eResource.errors
		Assertions.assertTrue(errors.isEmpty, '''Unexpected errors: «errors.join(", ")»''')
	}
}
