/*
 * generated by Xtext 2.17.0
 */
package com.foliage.xenia.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractXeniaScopeProvider extends DelegatingScopeProvider {
}
