/**
 * generated by Xtext 2.17.0
 */
package com.foliage.xenia.scoping;

import com.foliage.xenia.scoping.AbstractXeniaScopeProvider;

/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
@SuppressWarnings("all")
public class XeniaScopeProvider extends AbstractXeniaScopeProvider {
}
