/**
 * generated by Xtext 2.17.0
 */
package com.foliage.xenia;

import com.foliage.xenia.AbstractXeniaRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class XeniaRuntimeModule extends AbstractXeniaRuntimeModule {
}
