/**
 * generated by Xtext 2.17.0
 */
package com.foliage.xenia;

import com.foliage.xenia.XeniaStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class XeniaStandaloneSetup extends XeniaStandaloneSetupGenerated {
  public static void doSetup() {
    new XeniaStandaloneSetup().createInjectorAndDoEMFRegistration();
  }
}
