/**
 * generated by Xtext 2.17.0
 */
package com.foliage.xenia.validation;

import com.foliage.xenia.validation.AbstractXeniaValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class XeniaValidator extends AbstractXeniaValidator {
}
