/*
 * generated by Xtext 2.17.0
 */
package com.foliage.xenia.ui.tests;

import com.foliage.xenia.ui.internal.XeniaActivator;
import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;

public class XeniaUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return XeniaActivator.getInstance().getInjector("com.foliage.xenia.Xenia");
	}

}
