/**
 * generated by Xtext 2.17.0
 */
package com.foliage.xenia.ide;

import com.foliage.xenia.ide.AbstractXeniaIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class XeniaIdeModule extends AbstractXeniaIdeModule {
}
