/*
 * generated by Xtext 2.17.0
 */
package com.foliage.xenia


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class XeniaStandaloneSetup extends XeniaStandaloneSetupGenerated {

	def static void doSetup() {
		new XeniaStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
