/*
 * generated by Xtext 2.17.0
 */
package com.foliage.xenia.serializer;

import com.foliage.xenia.services.XeniaGrammarAccess;
import com.google.inject.Inject;
import java.util.List;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.IGrammarAccess;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.nodemodel.INode;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.AbstractElementAlias;
import org.eclipse.xtext.serializer.analysis.ISyntacticSequencerPDAProvider.ISynTransition;
import org.eclipse.xtext.serializer.sequencer.AbstractSyntacticSequencer;

@SuppressWarnings("all")
public class XeniaSyntacticSequencer extends AbstractSyntacticSequencer {

	protected XeniaGrammarAccess grammarAccess;
	
	@Inject
	protected void init(IGrammarAccess access) {
		grammarAccess = (XeniaGrammarAccess) access;
	}
	
	@Override
	protected String getUnassignedRuleCallToken(EObject semanticObject, RuleCall ruleCall, INode node) {
		if (ruleCall.getRule() == grammarAccess.getPropertyRule())
			return getPropertyToken(semanticObject, ruleCall, node);
		else if (ruleCall.getRule() == grammarAccess.getXtendedPropertyRule())
			return getXtendedPropertyToken(semanticObject, ruleCall, node);
		return "";
	}
	
	/**
	 * Property:
	 * 	'app' | 'with' | 'sitemap'
	 * ;
	 */
	protected String getPropertyToken(EObject semanticObject, RuleCall ruleCall, INode node) {
		if (node != null)
			return getTokenText(node);
		return "app";
	}
	
	/**
	 * XtendedProperty:
	 * 	'sites' | 'map' | 'info'
	 * ;
	 */
	protected String getXtendedPropertyToken(EObject semanticObject, RuleCall ruleCall, INode node) {
		if (node != null)
			return getTokenText(node);
		return "sites";
	}
	
	@Override
	protected void emitUnassignedTokens(EObject semanticObject, ISynTransition transition, INode fromNode, INode toNode) {
		if (transition.getAmbiguousSyntaxes().isEmpty()) return;
		List<INode> transitionNodes = collectNodes(fromNode, toNode);
		for (AbstractElementAlias syntax : transition.getAmbiguousSyntaxes()) {
			List<INode> syntaxNodes = getNodesFor(transitionNodes, syntax);
			acceptNodes(getLastNavigableState(), syntaxNodes);
		}
	}

}
